### ISSUE TITLE
Update the importlib-metadata to >=1.6.0 - After next poetry release >1.0.8

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/poetry-core-feedstock#25]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/python-poetry/poetry/commit/c5ac467f708f5be06b20078b0ed5b5fc427c6ff5

Poetry has updated the importlib-metadata to >=1.6.0

importlib-metadata = { version = ">=1.6.0", python = "<3.8" }

### Installed packages

```shell
NA
```

### Environment info

```shell
NA
```

**Comment by xylar** [comment]
@rxm7706, there has not yet been a non-beta release with the pins you are pointing to as far as I can tell.  The current pins are correct for the most recent release, take a look at: https://files.pythonhosted.org/packages/51/be/c4dce945cf7de2dc38d94cf724525f2a97d83b18403eeeb87eecb715dada/poetry-core-1.0.8.tar.gz
or
https://github.com/python-poetry/poetry-core/blob/1.0.8/pyproject.toml#L36

The link you posted is also to the `poetry`, rather than the `poetry-core` feedstock.  Perhaps that is also related?

**Comment by rxm7706** [comment]
@xylar you are right, I noticed that change has been made in poetry but not yet released. I'll update the Issue to highlight this needs to be done after the next poetry release.

**Comment by rxm7706** [comment]
https://github.com/conda-forge/poetry-feedstock/issues/61#issuecomment-1108221373
